apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokiuyftd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokiuyftd
  template:
    metadata:
      labels:
        app: pokiuyftd
    spec:
      containers:
      - image: okteto.dev/pokiuyftd:latest
        name: pokiuyftd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2d0173d8-7d0f-4a3c-8cc2-326d16317bc5"
        - name: Vless_Path
          value: "/vldfadfdffjuygrfg"
        - name: Vmess_UUID
          value: "2d0173d8-7d0f-4a3c-8cc2-326d16317bc5"
        - name: Vmess_Path
          value: "/vmolklyfghsedfr"
        - name: Share_Path
          value: "/v2link"
