apiVersion: apps/v1
kind: Deployment
metadata:
  name: okgsdrrtr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okgsdrrtr
  template:
    metadata:
      labels:
        app: okgsdrrtr
    spec:
      containers:
      - image: okteto.dev/okgsdrrtr:latest
        name: okgsdrrtr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4ee08abb-a03a-4c9c-8cde-fdd74f12c7ab"
        - name: Vless_Path
          value: "/vldfadfdffjuygrfg"
        - name: Vmess_UUID
          value: "4ee08abb-a03a-4c9c-8cde-fdd74f12c7ab"
        - name: Vmess_Path
          value: "/vmolklyfghsedfr"
        - name: Share_Path
          value: "/v2link"
